/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geometricart;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JPanel;

/**
 *
 * @author maria
 */
public class Canvas extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Canvas
     */
    public Canvas() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setForeground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(ActionEvent e) {
      repaint();
    }
   Random random=new Random();
    Painting painting ,secondshape,thirdshape,forthsape,fifthshape,sixthshape;
      Individual[] shapes,second,third,forth,fifth,sixth;
       Painting[] paintings;
    Shape_method triangle=new Shape_method();
      int selector;
    static int k=0;
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//       painting = new Painting();
//       shapes = painting.getShapes();

Dimension size = jPanel7.getSize();
int width = size.width;
int height = size.height;
System.out.println("Panel size is " + width + " x " + height);

        Creation_of_the_individual c=new Creation_of_the_individual();
       
       paintings= new Painting[10];
        for (int i = 0; i < 10; i++) {
            paintings[i] = new Painting();
        }
        painting=paintings[0];
        shapes=painting.getShapes();
        secondshape=paintings[1];
        second=secondshape.getShapes();
        thirdshape=paintings[2];
        third=thirdshape.getShapes();
        forthsape=paintings[3];
        forth=forthsape.getShapes();
        fifthshape=paintings[4];
        fifth=fifthshape.getShapes();
        sixthshape=paintings[5];
        sixth=sixthshape.getShapes();
   k++;
      System.out.print(k);
     
            int i;
    
      Graphics g = jPanel1.getGraphics();
      Graphics g2 = jPanel2.getGraphics();
      Graphics g3 = jPanel3.getGraphics();
      Graphics g4 = jPanel4.getGraphics();
      Graphics g5 = jPanel5.getGraphics();
      Graphics g6 = jPanel6.getGraphics();
    
      
     
           for( i=0;i<6;i++)
        {
            
       selector=random.nextInt(3);
        
      switch(shapes[i].getSelector())
              {
          case 0:
              
                   g.drawRect(shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());                  
                System.out.println(" square height : "+shapes[i].getHeight() + "square length : "+shapes[i].getLenght());
                
                  
                   break;
          case 1:
              g.drawOval(shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());
             System.out.println("oval height 1  "+ shapes[i].getHeight());
              break;
          case 2:triangle.drawTraingle(g, shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());
              
              }
      System.out.println("Selector: "+third[i].getSelector());
    
      switch(second[i].getSelector())
              {
          case 0:
              
                   g2.drawRect(second[i].getX(), second[i].getY(), second[i].getHeight(),second[i].getLenght());                  
                System.out.println("height second shape square : "+second[i].getHeight() + "length second shape square: "+second[i].getLenght());
                  
                   break;
          case 1:
              g2.drawOval(second[i].getX(), second[i].getY(), second[i].getHeight(),second[i].getLenght());
             System.out.println("height second shape  "+ second[i].getHeight());
              break;
           case 2:triangle.drawTraingle(g2, shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());

              
              }
//       selector=random.nextInt(3);
//      switch(selector)
//              {
//          case 0:
//              
//                   g3.drawRect(third[i].getX(), third[i].getY(), third[i].getHeight(),third[i].getLenght());                  
//                System.out.println("height second shape square : "+third[i].getHeight() + "length second shape square: "+third[i].getLenght());
//                  
//                   break;
//          case 1:
//              g3.drawOval(third[i].getX(), third[i].getY(), third[i].getHeight(),third[i].getLenght());
//             System.out.println("height second shape  "+ third[i].getHeight());
//              break;
//              
//              
//                     case 2:triangle.drawTraingle(g3, shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());
//
//              
//              }
//       selector=random.nextInt(3);
//       switch(selector)
//              {
//          case 0:
//              
//                   g4.drawRect(forth[i].getX(), forth[i].getY(), forth[i].getHeight(),forth[i].getLenght());                  
//                System.out.println("height second shape square : "+forth[i].getHeight() + "length second shape square: "+forth[i].getLenght());
//                  
//                   break;
//          case 1:
//              g4.drawOval(forth[i].getX(), forth[i].getY(), forth[i].getHeight(),forth[i].getLenght());
//             System.out.println("height second shape  "+ forth[i].getHeight());
//              break;
//                        case 2:triangle.drawTraingle(g4, shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());
//
//              
//              }
//        selector=random.nextInt(3);
//switch(selector)
//              {
//          case 0:
//              
//                   g5.drawRect(fifth[i].getX(), fifth[i].getY(), fifth[i].getHeight(),fifth[i].getLenght());                  
//                System.out.println("height second shape square : "+fifth[i].getHeight() + "length second shape square: "+fifth[i].getLenght());
//                  
//                   break;
//          case 1:
//              g5.drawOval(fifth[i].getX(), fifth[i].getY(), fifth[i].getHeight(),fifth[i].getLenght());
//             System.out.println("height second shape  "+ fifth[i].getHeight());
//              break;
//                        case 2:triangle.drawTraingle(g5, shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());
//
//              
//              }
// selector=random.nextInt(3);
//switch(selector)
//              {
//          case 0:
//              
//                   g6.drawRect(sixth[i].getX(), sixth[i].getY(), sixth[i].getHeight(),sixth[i].getLenght());                  
//                System.out.println("height second shape square : "+sixth[i].getHeight() + "length second shape square: "+fifth[i].getLenght());
//                  
//                   break;
//          case 1:
//              g6.drawOval(sixth[i].getX(), sixth[i].getY(), sixth[i].getHeight(),sixth[i].getLenght());
//             System.out.println("height second shape  "+ sixth[i].getHeight());
//              break;
//                        case 2:triangle.drawTraingle(g6, shapes[i].getX(), shapes[i].getY(), shapes[i].getHeight(),shapes[i].getLenght());
//
//              
//              }
  
      }
      
           
       
        
       
  
        
                        
    }//GEN-LAST:event_jButton1ActionPerformed
//end of function
    
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         // Print the attributes of each shape in each painting
         

        
        // Print the attributes of each shape in each painting
       
        repaint();
        if( shapes==null)
        {
            System.out.println("Nu exista picturi ");
        }
        else
        {
            for(int i=0;i<10;i++)
                
        {
            System.out.println("Shape "+i);
            shapes=paintings[i].getShapes();
            
            
            for(int j=0;j<6;j++)
            {
                System.out.println("height of the shape "+i+":"+shapes[j].getHeight());
                System.out.println("Selector"+third[j].getSelector());
            }
        }
        }
        
        
//         if(shapes ==null && second ==null)
//           {
//               System.out.println("No paintings");
//           }
//           else
//           {
//               for (int j = 0; j < 6; j++) {
//          
//                System.out.println("Shape " + (j+1) + " - Height: " + shapes[j].getHeight() + ", Length: " + shapes[j].getLenght() );
//                 System.out.println("Shape " + (j+1) + " - Height: " + second[j].getHeight() + ", Length: " + second[j].getLenght() );
//            }
//               
//           }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           
        Creation_of_the_individual creation=new Creation_of_the_individual();
        
        
        Graphics g7=jPanel7.getGraphics();
            shapes=paintings[2].getShapes();
            Individual[]s=paintings[3].getShapes();
          creation.Crossover(shapes, s);
            for(int i=0;i<10;i++)
        {
            shapes=paintings[i].getShapes();
            for(int j=0;j<6;j++)
            {
                System.out.println("height of the shape "+i+":"+shapes[j].getHeight());
            }
        }
            for(int i=0;i<6;i++)
        {
     
        
      switch(second[i].getSelector())
              {
          case 0:
              
                   g7.drawRect(second[i].getX(), second[i].getY(), second[i].getHeight(),second[i].getLenght());                  
                System.out.println(" square height : "+second[i].getHeight() + "square length : "+second[i].getLenght());
                
                  
                   break;
          case 1:
              g7.drawOval(second[i].getX(), second[i].getY(), second[i].getHeight(),second[i].getLenght());
             System.out.println("oval height 1  "+ second[i].getHeight());
              break;
          case 2:triangle.drawTraingle(g7, second[i].getX(), second[i].getY(), second[i].getHeight(),second[i].getLenght());
              
              }
        }
        
            
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Canvas can=new Canvas();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Canvas().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

 
}
